version: "3"

services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
  redis:
    image: 'redis:latest'
    ports:
      - "6378:6379"
  keycloak:
    container_name: keycloak
    command: start
    image: keycloak/keycloak:25.0.6
    ports:
      - 8080:8080
    environment:
      - KC_HOSTNAME= localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    restart: always
